name: Deploy CVWA
on:
  push:
    tags:
       - 'deploy-cvwa-*'
jobs:
  create-ec2:
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Install install-codedeploy-cvwa.sh
        id: wget-install-codedeploy-cvwa
        run: |
          echo '#!/bin/bash
          sudo apt-get update && sudo apt-get upgrade -y
          sudo apt-get install git apache2 php7.4-cli php7.4-fpm ruby-full libapache2-mod-php7.4 -y
          
          sudo systemctl reload apache2
          sudo systemctl enable apache2
          
          wget https://aws-codedeploy-us-east-2.s3.us-east-2.amazonaws.com/latest/install
          chmod +x install
          sudo ./install auto
          
          sudo service codedeploy-agent start' > install-codedeploy-cvwa.sh && chmod +x install-codedeploy-cvwa.sh

      - name: Create EC2
        id: create-ec2-tags
        run: |
          aws ec2 run-instances \
            --image-id ami-0629230e074c580f2 \
            --count 1 \
            --instance-type t2.micro \
            --key-name new-par-aws \
            --security-group-ids sg-0d40b040556c42d54 \
            --subnet-id subnet-06166ec0280d94c08 \
            --iam-instance-profile Name=CodeDeploy_EC2Role \
            --user-data file://install-codedeploy-cvwa.sh \
            --tag-specifications 'ResourceType=instance,Tags=[{Key=name,Value=ec2-deploy-cvwa}]'

  sleep-jobs-v1:
    runs-on: ubuntu-latest
    needs: [create-ec2]
    steps:
       - name: Sleep for 1min
         uses: juliangruber/sleep-action@v1
         with:
           time: 1m

  deployment-codedeploy:
    runs-on: ubuntu-latest
    needs: [sleep-jobs-v1]
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Create CodeDeploy Deployment
        id: deploy
        run: |
          aws deploy create-deployment \
            --application-name deploy-app-name-cvwa \
            --deployment-group-name grupo-deploy-app-cvwa \
            --deployment-config-name CodeDeployDefault.OneAtATime \
            --github-location repository=${{ github.repository }},commitId=${{ github.sha }}

  sleep-jobs-v2:
    runs-on: ubuntu-latest
    needs: [deployment-codedeploy]
    steps:
       - name: Sleep for 1min
         uses: juliangruber/sleep-action@v1
         with:
           time: 1m

  ec2-public-ip-address:
    runs-on: ubuntu-latest
    needs: [sleep-jobs-v2]
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: EC2 IP address
        id: ip-address
        run: aws ec2 describe-instances --filters "Name=tag:name,Values=ec2-deploy-cvwa" --query "Reservations[].Instances[].PublicIpAddress"